version: 2
jobs:
  build-chart:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          command: wget -O - https://raw.githubusercontent.com/int128/helm-github-pages/master/publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: int128/helm-charts
  check-and-push-latest:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add bash ca-certificates git openssh curl jq
      - run: ./.circleci/check-and-push-latest.sh

workflows:
  version: 2
  commit:
    jobs:
      - build-chart
      - check-and-push-latest
  daily-update:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check-and-push-latest
