apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gitbucket.fullname" $ }}
  labels:
    # standard labels: https://helm.sh/docs/topics/chart_best_practices/labels/#standard-labels
    app.kubernetes.io/name: {{ template "gitbucket.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}