name: test

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/test.yaml
      - Dockerfile
      - gitbucket.sh
    tags:
      - v*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/test.yaml
      - Dockerfile
      - gitbucket.sh

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - run: docker buildx build -t gitbucket .
      - run: docker run -d -p 8080:8080 --name gitbucket gitbucket
      - run: |
          while ! curl -v localhost:8080; do
            sleep 5
          done
      - run: docker stop gitbucket
      - run: docker logs gitbucket
